import { FormValues, ServiceDefinition, ServiceKey } from "./types";

export const defaultValues: FormValues = {
  fullName: "",
  email: "",
  phone: "",
  gender: "",
  question: "",
  focusArea: "",
  currentFeeling: "",
  propertyType: "",
  layoutLink: "",
  facingDirection: "",
  mainIssues: [],
  problemDescription: "",
  dateOfBirth: "",
  nickname: "",
  exactBirthTime: "",
  birthPlace: "",
  mainConcern: "",
  currentIssue: "",
  issueTypes: [],
  sessionType: "",
  timeSlot: "",
};

export const serviceDefinitions: Record<ServiceKey, ServiceDefinition> = {
  tarot: {
    key: "tarot",
    title: "Tarot Reading Intake",
    shortTitle: "Tarot Reading",
    icon: "✦",
    accent: "from-rose-400/30 via-fuchsia-300/20 to-amber-200/20",
    description: "A quick, heart-led check-in for the question weighing on you most.",
    microcopy: "Takes less than 1 minute ⏳",
    confidentialityNote: "100% confidential 🔒",
    price: 501,
    currency: "INR",
    calendlyUrl: "https://calendly.com/vedastraa/30min",
    steps: [
      {
        title: "Personal Energy",
        description: "Share the essentials so the reading feels personal and grounded.",
        fields: [
          { name: "fullName", label: "Full Name / Initials", type: "text", placeholder: "How should we address you?", required: true },
          { name: "email", label: "Email Address", type: "text", placeholder: "Where should we send your reading?", required: true },
          { name: "phone", label: "Phone Number", type: "text", placeholder: "For session updates", required: true },
          {
            name: "gender",
            label: "Gender",
            type: "select",
            placeholder: "Optional",
            options: [
              { label: "Woman", value: "Woman" },
              { label: "Man", value: "Man" },
              { label: "Non-binary", value: "Non-binary" },
              { label: "Prefer not to say", value: "Prefer not to say" },
            ],
          },
        ],
      },
      {
        title: "Your Question",
        description: "Tell us what needs clarity right now.",
        fields: [
          { name: "question", label: "Your Question", type: "textarea", placeholder: "What’s currently bothering you or what clarity do you seek?", required: true, rows: 5 },
          {
            name: "focusArea",
            label: "Area of Focus",
            type: "select",
            placeholder: "Choose an area",
            options: [
              { label: "Love ❤️", value: "Love ❤️" },
              { label: "Career 💼", value: "Career 💼" },
              { label: "Finance 💰", value: "Finance 💰" },
              { label: "General 🌿", value: "General 🌿" },
            ],
          },
          {
            name: "currentFeeling",
            label: "Current Feeling",
            type: "select",
            placeholder: "Optional",
            options: [
              { label: "Confused", value: "Confused" },
              { label: "Stuck", value: "Stuck" },
              { label: "Anxious", value: "Anxious" },
              { label: "Curious", value: "Curious" },
            ],
          },
        ],
      },
    ],
  },
  vastu: {
    key: "vastu",
    title: "Vastu Consultation Intake",
    shortTitle: "Vastu Consultation",
    icon: "◈",
    accent: "from-amber-300/30 via-sky-300/15 to-emerald-200/15",
    description: "A structured consultation form for understanding the energy of your space.",
    microcopy: "Takes less than 1 minute ⏳",
    confidentialityNote: "100% confidential 🔒",
    price: 2100,
    currency: "INR",
    calendlyUrl: "https://calendly.com/vedastraa/30min",
    steps: [
      {
        title: "Property Details",
        description: "Set the consultation context with your core property information.",
        fields: [
          { name: "fullName", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
          { name: "email", label: "Email Address", type: "text", placeholder: "Your email for consultation details", required: true },
          { name: "phone", label: "Phone Number", type: "text", placeholder: "For consultation updates", required: true },
          {
            name: "propertyType",
            label: "Property Type",
            type: "select",
            placeholder: "Select property type",
            required: true,
            options: [
              { label: "Home", value: "Home" },
              { label: "Office", value: "Office" },
              { label: "Shop", value: "Shop" },
            ],
          },
          { name: "layoutLink", label: "Google Drive Link (Layout/Photos)", type: "text", placeholder: "Paste your G-Drive link here", helperText: "Make sure link sharing is on 🔒" },
          {
            name: "facingDirection",
            label: "Facing Direction",
            type: "select",
            placeholder: "Select direction",
            required: true,
            options: [
              { label: "North", value: "North" },
              { label: "South", value: "South" },
              { label: "East", value: "East" },
              { label: "West", value: "West" },
            ],
          },
        ],
      },
      {
        title: "Consultation Concerns",
        description: "Tell us what patterns or disruptions you want the consultation to address.",
        fields: [
          {
            name: "mainIssues",
            label: "Main Issues",
            type: "checkbox-group",
            options: [
              { label: "Financial problems", value: "Financial problems" },
              { label: "Health issues", value: "Health issues" },
              { label: "Relationship issues", value: "Relationship issues" },
              { label: "Lack of growth", value: "Lack of growth" },
            ],
          },
          { name: "problemDescription", label: "Describe Your Problem", type: "textarea", placeholder: "Tell us what’s been going wrong...", required: true, rows: 5 },
        ],
      },
    ],
  },
  numerology: {
    key: "numerology",
    title: "Numerology Intake",
    shortTitle: "Numerology",
    icon: "⌘",
    accent: "from-indigo-300/25 via-cyan-200/15 to-amber-200/15",
    description: "A precise profile for name vibration and life-path guidance.",
    microcopy: "Takes less than 1 minute ⏳",
    confidentialityNote: "100% confidential 🔒",
    price: 1101,
    currency: "INR",
    calendlyUrl: "https://calendly.com/vedastraa/30min",
    steps: [
      {
        title: "Identity Details",
        description: "We use your exact name and birth date for accurate numerology calculations.",
        fields: [
          { name: "fullName", label: "Full Name", type: "text", placeholder: "As per official documents", helperText: "Name spelling affects numerology results", required: true },
          { name: "email", label: "Email Address", type: "text", placeholder: "Your email for the report", required: true },
          { name: "phone", label: "Phone Number", type: "text", placeholder: "For session updates", required: true },
          { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
        ],
      },
      {
        title: "Reading Focus",
        description: "Add any optional personal context for a sharper reading.",
        fields: [
          { name: "nickname", label: "Nickname", type: "text", placeholder: "Optional nickname" },
          {
            name: "focusArea",
            label: "Focus Area",
            type: "select",
            placeholder: "Choose focus area",
            required: true,
            options: [
              { label: "Career", value: "Career" },
              { label: "Marriage", value: "Marriage" },
              { label: "Personal growth", value: "Personal growth" },
            ],
          },
        ],
      },
    ],
  },
  astrology: {
    key: "astrology",
    title: "Vedic Astrology Intake",
    shortTitle: "Vedic Astrology",
    icon: "☼",
    accent: "from-violet-300/30 via-indigo-300/20 to-slate-100/10",
    description: "A trust-first birth details form for a precise Vedic astrology reading.",
    microcopy: "Takes less than 1 minute ⏳",
    confidentialityNote: "Your birth details are kept strictly confidential 🔒",
    price: 1501,
    currency: "INR",
    calendlyUrl: "https://calendly.com/vedastraa/30min",
    steps: [
      {
        title: "Birth Details",
        description: "Accurate birth information helps us interpret your chart correctly.",
        fields: [
          { name: "fullName", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
          { name: "email", label: "Email Address", type: "text", placeholder: "Your email for birth chart", required: true },
          { name: "phone", label: "Phone Number", type: "text", placeholder: "For consultation updates", required: true },
          { name: "dateOfBirth", label: "Date of Birth", type: "date", required: true },
          { name: "exactBirthTime", label: "Exact Time of Birth", type: "time", required: true },
          { name: "birthPlace", label: "Place of Birth", type: "text", placeholder: "City, Country", required: true },
        ],
      },
      {
        title: "Guidance Request",
        description: "Share what kind of guidance you want so the session feels relevant from the start.",
        fields: [
          {
            name: "gender",
            label: "Gender",
            type: "select",
            placeholder: "Optional",
            options: [
              { label: "Woman", value: "Woman" },
              { label: "Man", value: "Man" },
              { label: "Non-binary", value: "Non-binary" },
              { label: "Prefer not to say", value: "Prefer not to say" },
            ],
          },
          { name: "mainConcern", label: "Main Concern", type: "textarea", placeholder: "What do you want guidance on?", required: true, rows: 5 },
        ],
      },
    ],
  },
  healing: {
    key: "healing",
    title: "Energy Healing Intake",
    shortTitle: "Energy Healing",
    icon: "❋",
    accent: "from-emerald-200/30 via-cyan-200/20 to-sky-100/10",
    description: "A calm, spacious intake designed to feel safe and restorative.",
    microcopy: "Takes less than 1 minute ⏳",
    confidentialityNote: "100% confidential 🔒",
    price: 2501,
    currency: "INR",
    calendlyUrl: "https://calendly.com/vedastraa/30min",
    steps: [
      {
        title: "How You Feel",
        description: "Let us understand the emotional or mental load you’re carrying.",
        fields: [
          { name: "fullName", label: "Full Name", type: "text", placeholder: "Your full name", required: true },
          { name: "email", label: "Email Address", type: "text", placeholder: "Your email for healing session", required: true },
          { name: "phone", label: "Phone Number", type: "text", placeholder: "For session updates", required: true },
          { name: "currentIssue", label: "Current Issue", type: "textarea", placeholder: "What are you struggling with emotionally or mentally?", required: true, rows: 5 },
        ],
      },
      {
        title: "Session Preferences",
        description: "Choose the kind of support and rhythm that feels right for you.",
        fields: [
          {
            name: "issueTypes",
            label: "Type of Issue",
            type: "checkbox-group",
            required: true,
            options: [
              { label: "Stress", value: "Stress" },
              { label: "Anxiety", value: "Anxiety" },
              { label: "Negative energy", value: "Negative energy" },
              { label: "Relationship pain", value: "Relationship pain" },
              { label: "Lack of focus", value: "Lack of focus" },
            ],
          },
          {
            name: "sessionType",
            label: "Preferred Session Type",
            type: "radio-group",
            required: true,
            options: [
              { label: "Live session", value: "Live session" },
              { label: "Distant healing", value: "Distant healing" },
            ],
          },
          {
            name: "timeSlot",
            label: "Preferred Time Slot",
            type: "select",
            placeholder: "Select a time slot",
            required: true,
            options: [
              { label: "Morning", value: "Morning" },
              { label: "Afternoon", value: "Afternoon" },
              { label: "Evening", value: "Evening" },
            ],
          },
        ],
      },
    ],
  },
};
